#pragma kernel CSMain

struct Point
{
    float depth;
    uint id;
};

Texture2D<float4> Input;
RWStructuredBuffer<Point> Output;

uint NumIDs;

[numthreads(8,8,1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    float4 color = Input[id.xy];

    Point p;
    p.depth = color.r;
    p.id = round(color.g * NumIDs);

    float width, height;
    Input.GetDimensions(width, height);
    Output[id.x + id.y * width] = p;
}
